### PR TITLE
Added argument DELETE_OLDER_THAN to automatically delete old s3 backups

### PR DESCRIPTION
**Pull request by zhonghuiwen**

### CODE REVIEW

**Comment by OlivierCuyp** [comment]
hi @zhonghuiwen,

First why don't you use `AWS S3 Life Cycle` settings to delete your old backups ?

Then to backup folder, you can use [schickling/s3cmd](https://github.com/schickling/dockerfiles/tree/master/s3cmd).
Here is how I use it to backup my NAS:

```
docker run -e SCHEDULE="0 0 0 * * *" -v (pwd)/data:/s3 schickling/s3cmd --access_key=<MY_ACCESS_KEY> --secret_key=<MY_SECRET_KEY> sync . s3://my.bucket
```

I'm sure s3cmd is flexible enough to do whatever you need.

**Comment by OlivierCuyp** [comment]
@zhonghuiwen, I'm not that familiar with Minio. But it seems you can use [schickling/s3cmd](https://github.com/schickling/dockerfiles/tree/master/s3cmd) : 
https://docs.minio.io/docs/s3cmd-with-minio

Then for the lifecycle, unfortunately it isn't implemented yet. But it is in the planning according the last comment here:
https://github.com/minio/minio/issues/5139

So thanks a lot for your PR, but I believe this would be a temporary fix for a specific case.
Let us know if you encounter some issue running [schickling/s3cmd](https://github.com/schickling/dockerfiles/tree/master/s3cmd) with Minio. That's always interesting for us and others.

**Comment by zhonghuiwen** [comment]
Oh Thanks @OlivierCuyp ! didn't know that lifecycle for minio is in the works

**Comment by OlivierCuyp** [comment]
@zhonghuiwen no problem, happy to help. Thanks for your initiative, don't hesitate if you have other ideas

**Pull request closed without merging**
