### PR TITLE
Update swagger-ui to v3.0.4

### PR DESCRIPTION
**Pull request by Robbilie**

### CODE REVIEW

**Comment by schickling** [comment]
Did you test this already @Robbilie?

**Comment by Robbilie** [comment]
Just changed the versions like in previous commits, I can try it in a few minutes

**Comment by Robbilie** [comment]
@schickling
http://138.201.40.82:12345/
docker run -d -p 12345:80 -e API_URL="https://esi.tech.ccp.is/latest/swagger.json" -e OAUTH_CLIENT_ID="3a7d1f1207a04b32b7d27feca20748f2" -e OAUTH_REALM="ESI" -e OAUTH_APP_NAME="ESI Swagger UI (self-hosted)" swaggerui

- [ ] doesnt use the client id
- [ ] complains that no redirect uri is set

**Comment by elberth90** [comment]
@schickling @Robbilie what's the status of this PR?

**Comment by Robbilie** [comment]
@elberth90 im on vacation and haven't looked further into how to fix the issues I listed, maybe someone can take a quick look? Shouldn't be much effort :3

**Pull request closed without merging**
