### PR TITLE
feat(postgres-backup-s3): Support custom backup filename

### PR DESCRIPTION
**Pull request by atoff**
As part of my use case with backups to S3, I prefer for my backups not to have unique filenames (i.e. timestamps) so that I can use lifecycle rules to appropriately expire non-current versioned items. This feature was previously supported by your `mysql-backup-s3` image, however it doesn't appear to be possible in this image for postgresql.

This PR:

- Updates the `postgresql-client` to support PostgreSQL 15
- Introduces the `S3_FILE_NAME` environment variable which, when supplied, is used as the file name instead of `<db>_<timestamp>.sql.gz`
- Removes `S3_BACKUP` env variable initialisation in the Dockerfile as this appears not to be used

Please let me know if any changes are needed to allow this to be accepted!

### CODE REVIEW

**Comment by iloveitaly** [comment]
@atoff looks great! Could you add a quick note to the readme about this one?

**Comment by atoff** [comment]
> @atoff looks great! Could you add a quick note to the readme about this one?

No worries - I've added a change to apply this to the dump_all option as well 😊

**Comment by atoff** [comment]
Hey @iloveitaly, any chance of getting this merged? Would love to start using it 😁

**Comment by iloveitaly** [comment]
@atoff just merged! Thanks for the contribution. I need to update all of the CI stuff to auto-update the Docker hub images, but I don't have the time right now (feel free to sponsor me if you'd like me to dedicate more time to it!).

**Pull request merged**
