### PR TITLE
Update postgres-backup-s3

### LINKED ISSUE #10: Backup all PostgresSQL databases
Can `pg_dumpall` be used instead of `pg_dump` if no database name was specified? I'm not truly familiar with dump/restore of PostgresSQL databases, but if you agree I can try to make a PR with this.

### LINKED ISSUE #59: Undefined $S3_PREFIX results in nameless directory in s3
As per the title, by not setting `S3_PREFIX` I assumed all backups would go into the root of my dedicated backup bucket however the backup files end up under an unnamed directory when viewing the AWS S3 console.

`cat dump.sql.gz | aws s3 cp - s3://$S3_BUCKET/$S3_PREFIX/$(date +"%Y-%m-%dT%H:%M:%SZ").sql.gz || exit 2`

I assume the extraneous `/` needs to be removed if `$S3_PREFIX` isn't provided.

### LINKED ISSUE #87: postgres-backup-s3: Missing variable from example
The example for docker-compose is missing the ``POSTGRES_HOST`` environment variable.

### LINKED ISSUE #115: postgres-backup-s3: V11 not supported
Backing up a PostgreSQL v11.2 database fails. From the logs:

```
2019/03/31 00:00:00 17 cmd: /bin/sh backup.sh
2019/03/31 00:00:00 17: Creating dump of example database from db...
2019/03/31 00:00:00 17: pg_dump: 
2019/03/31 00:00:00 17: server version: 11.2; pg_dump version: 10.4
2019/03/31 00:00:00 17: pg_dump: 
2019/03/31 00:00:00 17: aborting because of server version mismatch
2019/03/31 00:00:00 17 Exit Status: 1
```

It seems that the Docker image is a bit outdated and should be rebuild.

### PR DESCRIPTION
**Pull request by blz-ea**
- Bump alpine from 3.9 to 3.11
- Add Postgres v12 support (Fixes #115)
- Add multiple or all databases backup (Fixes #10)
- S3_PREFIX can be empty (Fixes #59)
- Add missing Documentation (Fixes #87)

### CODE REVIEW

**Comment by unicod3** [comment]
Hello @schickling,

First thank you for these awesome images. 🥳 

Is there a plan for this PR to be accepted?

**Comment by iloveitaly** [comment]
@unicod3 @blz-ea This looks like a great change! Could you rebase on master to resolve the merge conflict here?

**Comment by Christilut** [comment]
Would be great if this can get merged!

**Comment by iloveitaly** [comment]
@blz-ea there are some merge conflicts here. Can you rebase?

I can merge and get a new image on hub.

**Comment by blz-ea** [comment]
@iloveitaly 🤔  . I do not see merge conflicts

Screen Shot 2022-01-21 at 11 58 11 AM

**Comment by iloveitaly** [comment]
Ah, I was looking at the wrong merge view.

**Pull request merged**
